#!/usr/bin/env python3
"""Update conversations.csv with a title column generated by Ollama phi4-mini."""

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from vectordb_learn.logging import setup_logging
from vectordb_learn.embedding.ollama import generate_title

setup_logging()

import structlog

log = structlog.get_logger()


def main():
    input_path = "data/conversations.csv"
    output_path = "data/conversations.csv"

    log.info("Starting title generation", input_path=input_path)

    rows = []
    with open(input_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            log.debug("Generating title for conversation", username=row['username'])
            title = generate_title(row['session_content'])
            rows.append({
                'username': row['username'],
                'session_content': row['session_content'],
                'title': title
            })

    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=['username', 'session_content', 'title'])
        writer.writeheader()
        writer.writerows(rows)

    log.info("Title generation complete", rows_updated=len(rows))

if __name__ == "__main__":
    main()
